cmake_minimum_required(VERSION 3.10)
project(untitled-battle C)
if((NOT DEFINED CMAKE_BUILD_TYPE) OR (CMAKE_BUILD_TYPE STREQUAL ""))
	set(CMAKE_BUILD_TYPE Release)
	set(CBT_ISDEF " (default)")
else()
	set(CBT_ISDEF "")
endif()
message("-- ${PROJECT_NAME}->CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}${CBT_ISDEF}")
set(CMAKE_C_FLAGS_RELEASE "-O3")
set(CMAKE_C_FLAGS_DEBUG "-Og -g -fsanitize=address")
set(CMAKE_C_FLAGS_MINSIZEREL "-Os")
set(CMAKE_C_FLAGS_RELWITHDEBINFO "-O2 -g")
add_compile_options(-Wall -Werror)
include_directories(src/include)
aux_source_directory(src/battle-lib BATTLE_LIB)
add_library(battle ${BATTLE_LIB})
target_link_libraries(battle INTERFACE m)
add_executable(ubt src/main.c)
add_executable(nbtdump src/nbtdump.c)
add_executable(nbtedit src/nbtedit.c)
add_executable(list src/list.c)
target_link_libraries(ubt battle ncursesw)
target_link_libraries(nbtdump battle)
target_link_libraries(nbtedit battle ncursesw)
target_link_libraries(list battle)
file(COPY zh_CN.lang DESTINATION ${PROJECT_BINARY_DIR})
